import { PredictionState } from '../prediction/types';
import { AgentRecommendation } from './types';

export class CoordinatorAgent {
  
  public process(state: PredictionState): AgentRecommendation[] {
    const recommendations: AgentRecommendation[] = [];

    // Analyze risks generated by the prediction engine
    state.risks.forEach(risk => {
      if (risk.category === 'transport_surge' && risk.targetId === 'g6') {
        recommendations.push({
          id: `rec_volunteer_${Date.now()}`,
          domain: 'volunteer',
          action: 'Reassign 5 volunteers from South Concourse to Gate 6',
          reasoning: `Expected metro surge in ${risk.timeToImpactMinutes} minutes will overwhelm current staff.`,
          priority: 'high'
        });
        
        recommendations.push({
          id: `rec_nav_${Date.now()}`,
          domain: 'navigation',
          action: 'Redirect incoming general admission to Gate 1',
          reasoning: 'Gate 6 is projected to hit 100% capacity; Gate 1 has 55% reserve capacity.',
          priority: 'medium'
        });
      }

      if (risk.category === 'gate_overload') {
        recommendations.push({
          id: `rec_crowd_${Date.now()}_${risk.targetId}`,
          domain: 'crowd',
          action: `Open overflow lanes at ${risk.targetId}`,
          reasoning: `Capacity is critically high. Wait times are unacceptable.`,
          priority: 'critical'
        });
      }
    });

    // Sustainability check
    if (state.currentTelemetry.sustainability.energyUsageKw > 4000) {
      recommendations.push({
        id: `rec_sust_${Date.now()}`,
        domain: 'sustainability',
        action: 'Dim concourse lighting by 15%',
        reasoning: 'Energy usage exceeds target threshold. Impact on visibility is negligible during daylight.',
        priority: 'low'
      });
    }

    return recommendations;
  }
}

export const coordinatorAgent = new CoordinatorAgent();
